### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by Ethck** [Ethck/uwInfo201Group6#1]
These questions need to be answered and submitted:

    What is the dataset you'll be working with?  Please include background on who collected the data, where you accessed it, and any additional information we should know about how this data came to be.
    Who is your target audience?  Depending on the domain of your data, there may be a variety of audiences interested in using the dataset.  You should home in on one of these audiences.
    What does your audience want to learn from your data?  Please list out at least 3 specific questions that your project will answer for your audience.

**Comment by sagnikshaggy** [comment]
[](url)

**Comment by sagnikshaggy** [comment]
[Project Description.docx](https://github.com/Ethck/uwInfo201Group6/files/3176244/Project.Description.docx)

**Comment by Ethck** [comment]
[Info201Proposal.docx](https://github.com/Ethck/uwInfo201Group6/files/3179652/Info201Proposal.docx)
